parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

github_checks:
  annotations: false

ignore:
  - "build"  # Ignore test coverage for generated files.
  - "utility_boilerplate_qt5/build"