parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

coverage:
  status:
    patch:
      default: false

ignore:
  - "build"  # Ignore test coverage for generated files.
  - "src/utility_boilerplate_qt5/build"