name: Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install project dependencies
        run: |
          sudo apt install qt5-default qttools5-dev-tools

      - name: Install format dependencies
        run: |
          sudo apt install clang-format
          pip3 install cmake_format==0.6.11 pyyaml

      - name: configure
        run: cmake -S ./ -B build/style

      - name: check style
        run: cmake --build build/style --target check-format
