name: Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install project dependencies
        run: |

      - name: Install format dependencies
        run: |
          sudo apt install clang-format
          pip3 install cmake_format==0.6.11 pyyaml

      - name: Configure
        run: cmake -S. -Bbuild/style

      - name: Style check
        run: cmake --build build/style --target check-format
