name: Ubuntu tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  QT_DEBUG_PLUGINS: 1
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: '5.15.2'

      - name: Install project dependencies
        run: |

      - name: Configure
        run: |
          cmake -S. -Bbuild/tests -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=1

      - name: Build
        run: cmake --build build/tests -j4

      - name: Test
        run: |
          cd build/tests
          ctest -V
          ctest -V -T coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/tests/Testing/CoverageInfo
          fail_ci_if_error: true
          verbose: true
