name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install project dependencies
        run: |
          sudo apt install qt5-default qttools5-dev-tools

      - name: Configure
        run: |
          xrandr --fb 1920x1080
          cmake -S. -Bbuild/tests -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build/tests -j4

      - name: Test
        run: |
          cd build/tests
          ctest --build-config Debug

      - name: Collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"